language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  - "pypy"
install:
  - "pip install protobuf"
  - "pip install colorama"
script:
  - python -m compileall -f .
  - python src/setup.py test
