apiVersion: v1
kind: Service
metadata:
  name: back1-svc
  labels:
    app: back1
    tier: backend
    role: master
spec:
  clusterIP: None # will return multiple A-records from DNS
  ports:
  - port: 8040
    targetPort: 8040
    name: backend
  selector:
    app: back1
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: back1
        tier: backend
        role: master
    spec:
      terminationGracePeriodSeconds: 300 # 5min to handle SIGTERM
      containers:
      - name: back1
        image: xebxeb/pysimserv:latest
        args:
        - --type=back
        - --name=back1
        - --port=8040
        ports:
        - name: back
          containerPort: 8040
        # resources:
        #   requests:
        #     cpu: 250m
        #     memory: 500Mi
---
